"""add posts, post_vectors, image_vectors, suggestions, reviews

Revision ID: 1cbe72cadd59
Revises: 83f6b14db182
Create Date: 2026-09-29 19:55:07.088253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '1cbe72cadd59'
down_revision: Union[str, None] = '83f6b14db182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_vectors',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('image_id', sa.BIGINT(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=768), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id')
    )
    op.create_index(op.f('ix_image_vectors_tenant_id'), 'image_vectors', ['tenant_id'], unique=False)
    op.create_table('post_vectors',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('post_id', sa.BIGINT(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=768), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    op.create_index(op.f('ix_post_vectors_tenant_id'), 'post_vectors', ['tenant_id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('taxon', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('subject_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_category'), 'posts', ['category'], unique=False)
    op.create_index(op.f('ix_posts_taxon'), 'posts', ['taxon'], unique=False)
    op.create_index(op.f('ix_posts_tenant_id'), 'posts', ['tenant_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('suggestion_id', sa.BIGINT(), nullable=False),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_suggestion_id'), 'reviews', ['suggestion_id'], unique=False)
    op.create_table('suggestions',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('post_id', sa.BIGINT(), nullable=False),
    sa.Column('image_id', sa.BIGINT(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('guard_checks', sa.JSON(), nullable=False),
    sa.Column('review_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'image_id')
    )
    op.create_index(op.f('ix_suggestions_post_id'), 'suggestions', ['post_id'], unique=False)
    op.create_index(op.f('ix_suggestions_tenant_id'), 'suggestions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suggestions_tenant_id'), table_name='suggestions')
    op.drop_index(op.f('ix_suggestions_post_id'), table_name='suggestions')
    op.drop_table('suggestions')
    op.drop_index(op.f('ix_reviews_suggestion_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_posts_tenant_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_taxon'), table_name='posts')
    op.drop_index(op.f('ix_posts_category'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_post_vectors_tenant_id'), table_name='post_vectors')
    op.drop_table('post_vectors')
    op.drop_index(op.f('ix_image_vectors_tenant_id'), table_name='image_vectors')
    op.drop_table('image_vectors')
    # ### end Alembic commands ###
