"""create images, image_metadata, jobs, cost_log

Revision ID: 83f6b14db182
Revises: 
Create Date: 2026-09-29 19:07:54.652684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83f6b14db182'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_log',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('job_id', sa.BIGINT(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('call_type', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('est_cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('ref_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_log_created_at'), 'cost_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_cost_log_job_id'), 'cost_log', ['job_id'], unique=False)
    op.create_table('image_metadata',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('image_id', sa.BIGINT(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('taxon', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('attributes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('needs_review', sa.Integer(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id')
    )
    op.create_index(op.f('ix_image_metadata_category'), 'image_metadata', ['category'], unique=False)
    op.create_index(op.f('ix_image_metadata_taxon'), 'image_metadata', ['taxon'], unique=False)
    op.create_index(op.f('ix_image_metadata_tenant_id'), 'image_metadata', ['tenant_id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_index(op.f('ix_images_tenant_id'), 'images', ['tenant_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('run_after', sa.DateTime(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('locked_by', sa.String(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('progress', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_run_after'), 'jobs', ['run_after'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_tenant_id'), 'jobs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_tenant_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_run_after'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_images_tenant_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_image_metadata_tenant_id'), table_name='image_metadata')
    op.drop_index(op.f('ix_image_metadata_taxon'), table_name='image_metadata')
    op.drop_index(op.f('ix_image_metadata_category'), table_name='image_metadata')
    op.drop_table('image_metadata')
    op.drop_index(op.f('ix_cost_log_job_id'), table_name='cost_log')
    op.drop_index(op.f('ix_cost_log_created_at'), table_name='cost_log')
    op.drop_table('cost_log')
    # ### end Alembic commands ###
